name: Skylife
version: '0.1'
main: love.chihuyu.skylife.Skylife
api-version: 1.18
authors: [ Hirosuke, Tenzyu ]
description: Original skyblock plugin for chihuyu.
website: chihuyu.love
commands:
  barter:
    aliases:
      - "ba"
  gacha:
    aliases:
      - "ga"
permissions:
  skylife.command.*:
    default: op
    children:
      skylife.command.barter: true
      skylife.command.gacha: true
  skylife.command.barter:
    default: true
  skylife.command.gacha:
    default: op