name: Skylife
version: '0.1'
main: love.chihuyu.skylife.Skylife
api-version: 1.18
authors: [ Hirosuke, Tenzyu ]
description: Original skyblock plugin for chihuyu.
website: chihuyu.love
commands:
  barter:
    aliases:
      - "ba"
      - "trade"
  gacha:
    aliases:
      - "ga"
  gachagive:
    aliases:
      - "gag"
permissions:
  skylife.command.*:
    default: op
  skylife.command.barter:
    default: true
  skylife.command.gacha:
    default: true
